apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stdtrinfra-ingress-synology
  namespace: synology
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.stdtrinfra.com"
      secretName: stdtrinfra-tls
  rules:
    - host: nas.stdtrinfra.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nas-svc
                port:
                  number: 5001
