apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stdtrinfra-ingress-static-file-server
  namespace: static-file-server
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.stdtrinfra.com"
      secretName: stdtrinfra-tls
  rules:
    - host: file.stdtrinfra.com
      http:
        paths:
          - path: /download
            pathType: Prefix
            backend:
              service:
                name: static-file-server-service
                port:
                  number: 80