apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkwarden-auth-rewrite-ingress
  namespace: linkwarden
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/auth/$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bookmark.stdtrinfra.com
      secretName: stdtrinfra-tls
  rules:
    - host: bookmark.stdtrinfra.com
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: linkwarden-svc
                port:
                  number: 3000
