apiVersion: v1
kind: Secret
metadata:
  name: airflow-api-keycloak
  namespace: insight
type: Opaque
stringData:
  CLIENT_ID: "airflow"
  CLIENT_SECRET: "${OAUTH2_CLIENT_SECRET}"
  OIDC_ISSUER: "https://keycloak.stdtrinfra.com/realms/tr-infra"
  AIRFLOW__API__BASE_URL: "https://airflow.stdtrinfra.com"