apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stdtrinfra-ingress-elastic-stack
  namespace: insight
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-elastic.stdtrinfra.com/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2-elastic.stdtrinfra.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-reqeust-user, x-auth-request-email, x-auth-request-access-token"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.stdtrinfra.com"
      secretName: stdtrinfra-tls
  rules:
    - host: elastic.stdtrinfra.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601